# Generated by Django 5.2.1 on 2025-06-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('change_own_review', 'Peut modifier sa propre critique')]},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('change_own_ticket', 'Peut modifier son propre ticket')]},
        ),
    ]
