# Generated by Django 5.2.3 on 2025-06-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_rename_time_created_ticket_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
    ]
